# Generated by Django 4.2.5 on 2023-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=100)),
                ("CampaingsPhoto", models.ImageField(upload_to="images/campaings")),
                ("CampaingsPhotoXl", models.ImageField(upload_to="images/campaings")),
            ],
        ),
    ]
