# Generated by Django 4.2.5 on 2023-09-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0002_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="searchbackground",
            field=models.ImageField(
                default="gecici_deger.jpg", upload_to="images/logo"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="logo",
            name="logo",
            field=models.ImageField(upload_to="images/logo"),
        ),
    ]
