# Generated by Django 4.2.5 on 2023-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0002_appuser_is_staff_alter_appuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
